### ISSUE TITLE
Calendar feeds?

### ISSUE THREAD

**Issue by ticky** [misenhower/splatoon2.ink#14]
I’d be interested in getting, say, Salmon Run schedule information in ics format for adding to my calendar. Is this something a PR might be accepted for, or would it be better to run it as a separate application?

**Comment by misenhower** [comment]
That's a cool idea. You could probably override `processData` in `CoopSchedulesUpdater` to output the calendar file to disk, or maybe make it a part of the core `Updater` class so it can be used in other updaters as well (I could see this being useful for Splatfests in particular).

I had previously used [this](https://github.com/mozilla-comm/ical.js) package to retrieve Salmon Run data from someone who maintained a schedule on Google Calendar -- I'm not sure if that library supports creating ical files as well as parsing them, but it would probably be worth a look.

I'd be open to a PR on this, or I could take a look at implementing it in the next few weeks or so. Thanks!

**Comment by ticky** [comment]
Thanks for the hints! I might have a go at adding it, then 😄

**Comment by misenhower** [comment]
Hey, first off, sorry it took me so long to get to this!

I made some changes to the calendar updating code so it could be reused more easily across different updaters. I also added calendars for Splatfests in each region.

I haven't added any public links on the site just yet since I figured I'd just let it run for a little while to make sure it works properly. If everything looks good I'll add some links and make an announcement on Twitter next week or so.

Also, for now I'm only providing feeds in English. I might add the other languages eventually, but I didn't want to make things too complicated for now.

Here are the URLs:

* https://splatoon2.ink/data/coop-schedules.ics
* https://splatoon2.ink/data/festivals-na.ics
* https://splatoon2.ink/data/festivals-eu.ics
* https://splatoon2.ink/data/festivals-jp.ics

Let me know if you notice any issues, and thanks again for your help!

**Comment by ticky** [comment]
Hey! This is great! Thanks for taking my idea and running with it 😄 it’s cool to see.

From popping it into my calendar program, it’s looking good! It feels a little unnecessary, given they’re in different feeds, to prepend Splatfest event titles with the region, but otherwise it looks really good!

When you’re happy with it, this looks good to close

**Comment by frozenpandaman** [comment]
This is cool. :)

**Comment by misenhower** [comment]
I think I'm happy with the region names in the title since this is how it shows up in Google Calendar:
![image](https://user-images.githubusercontent.com/1619746/42138400-dda5ea3a-7d31-11e8-9378-2de8127fa4c8.png)

I just added a dialog with subscription links to each of the calendars: https://splatoon2.ink/calendars

Going to tweet out a link here shortly. Thanks again!
