### ISSUE TITLE
[Suggestion] Rate limit for API

### ISSUE THREAD

**Issue by DatMayo** [misenhower/splatoon2.ink#20]
Hey,

when you're using npm for package managing, you could use [express-rate-limit](https://www.npmjs.com/package/express-rate-limit) for your data access policy :)

**Comment by misenhower** [comment]
In general I think that's a good idea, as I have had some issues with runaway bots hammering the server with tens of thousands of requests every hour (but those issues have been rare, and I've been able to block their IPs, etc.).

I'm not actually using Express to host the site, it's all just plain static files served with nginx. (There is one place where Express is used for generating screenshots for Twitter, but that's just internal access.) That said, the site is hosted behind CloudFlare so that helps with attacks somewhat.

I might look into some options with CloudFlare or rate limiting within nginx directly.
