### ISSUE TITLE
Add Translations for weapons/staged

### ISSUE THREAD

**Issue by Marionaise** [misenhower/splatoon2.ink#8]
Hey,

on your splatoon2.ink website, there is a translation for a lot languages.
Unfortunately not here, is it posibile to get this? :)

**Comment by misenhower** [comment]
Hey there,

Localized names for stages, weapons, and gear are loaded dynamically from SplatNet as they appear on the site. Since they're not hardcoded in the repository here, I don't have to do anything when a new stage or weapon comes out -- the site just updates automatically.

You can find all of the translated names that have been gathered so far by looking at the locale files on the site:
* [English](https://splatoon2.ink/data/locale/en.json)
* [Spanish](https://splatoon2.ink/data/locale/es.json)
* [Spanish (Mexico)](https://splatoon2.ink/data/locale/es-MX.json)
* [French](https://splatoon2.ink/data/locale/fr.json)
* [French (Canada)](https://splatoon2.ink/data/locale/fr-CA.json)
* [German](https://splatoon2.ink/data/locale/de.json)
* [Dutch](https://splatoon2.ink/data/locale/nl.json)
* [Italian](https://splatoon2.ink/data/locale/it.json)
* [Russian](https://splatoon2.ink/data/locale/ru.json)
* [Japanese](https://splatoon2.ink/data/locale/ja.json)

These do not contain a complete list of gear or weapons, though, as they only contain the items that have appeared on the site since I posted the internationalized version a few days ago.

I could probably retrieve a full list of weapon translations, let me know if that would help 🙂

**Comment by Marionaise** [comment]
A complete translation for german would be nice :)

**Comment by misenhower** [comment]
Here's a list of weapons (and sub/specials) in German: https://gist.github.com/misenhower/51146a5e2e81536e9e0f51fa48a15643

Unfortunately I can't retrieve information about gear as easily, but Inkipedia has translated names for a lot of the gear:
* [Headgear](https://splatoonwiki.org/wiki/List_of_headgear_in_Splatoon_2)
* [Clothing](https://splatoonwiki.org/wiki/List_of_clothing_in_Splatoon_2)
* [Shoes](https://splatoonwiki.org/wiki/List_of_shoes_in_Splatoon_2)

**Comment by Marionaise** [comment]
Hey,

big thx :)

**Comment by Marionaise** [comment]
Changed your JSON, so that you can use it with the standard definition @ Details -> Weapons
https://gist.github.com/Marionaise/a5b9379ec4d924992490e7ff3680a689
